# Generated by Django 5.2.7 on 2025-11-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Orders", "0002_alter_orderitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Placed", "Placed"),
                    ("Confirmed", "Confirmed"),
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
