# Generated by Django 5.2.7 on 2026-01-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0008_userprofile_last_notification_and_more"),
        ("Orders", "0004_alter_orderitem_order_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="adress",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Account.address",
            ),
        ),
    ]
