# Generated by Django 5.2.7 on 2025-12-01 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nume", models.CharField(max_length=50)),
                ("cod", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "valoare_discount",
                    models.IntegerField(help_text="Procent reducere %"),
                ),
                ("data_creare", models.DateTimeField(auto_now_add=True)),
                ("data_expirare", models.DateField()),
                ("subiect", models.CharField(blank=True, max_length=200, null=True)),
                ("mesaj", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoriePromotie",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "categorie",
                        "promotie",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CategoriePromotii",
                        to="Products.category",
                    ),
                ),
                (
                    "promotie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CategoriiPromotie",
                        to="Promotions.promotie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vizualizare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_vizualizare", models.DateTimeField(auto_now_add=True)),
                (
                    "produs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Vizualizari",
                        to="Products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Vizualizari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
