# Generated by Django 5.2.7 on 2025-11-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_adressuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
