# Generated by Django 5.2.7 on 2025-11-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0003_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="Name",
            new_name="name",
        ),
    ]
