# Generated by Django 5.2.7 on 2025-11-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0005_address_user_delete_adressuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cod",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_confirmat",
            field=models.BooleanField(default=False),
        ),
    ]
