# Generated by Django 5.2.7 on 2025-12-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0006_userprofile_cod_userprofile_email_confirmat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": [
                    (
                        "vizualizeaza_oferta",
                        "Poate vizualiza oferta speciala de reducere",
                    )
                ]
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="blocat",
            field=models.BooleanField(
                default=False,
                help_text="Daca este bifat, utilizatorul nu se poate loga.",
            ),
        ),
    ]
