# Generated by Django 5.2.7 on 2026-01-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0007_alter_userprofile_options_userprofile_blocat"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_notification",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="needs_profile_notification",
            field=models.BooleanField(default=False),
        ),
    ]
